ALTER TABLE users ADD creation_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE authors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NULL NULL,
  creation_date TEXT NOT NULL
);

PRAGMA user_version = 2;